Traceback (most recent call last):
  File "c:\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\matth\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "c:\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\python39\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\python39\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load image
image_1 = cv2.imread('../../data/greenscreen_1.jpg')
image_2 = cv2.imread('../../data/greenscreen_2.jpg')

# Convert to rgb
image_1 = cv2.cvtColor(image_1, cv2.COLOR_BGR2RGB)
image_2 = cv2.cvtColor(image_2, cv2.COLOR_BGR2RGB)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31merror[0m                                     Traceback (most recent call last)
Cell [1;32mIn[3], line 6[0m
[0;32m      3[0m image_2 [38;5;241m=[39m cv2[38;5;241m.[39mimread([38;5;124m'[39m[38;5;124m../../data/greenscreen_2.jpg[39m[38;5;124m'[39m)
[0;32m      5[0m [38;5;66;03m# Convert to rgb[39;00m
[1;32m----> 6[0m image_1 [38;5;241m=[39m [43mcv2[49m[38;5;241;43m.[39;49m[43mcvtColor[49m[43m([49m[43mimage_1[49m[43m,[49m[43m [49m[43mcv2[49m[38;5;241;43m.[39;49m[43mCOLOR_BGR2RGB[49m[43m)[49m
[0;32m      7[0m image_2 [38;5;241m=[39m cv2[38;5;241m.[39mcvtColor(image_2, cv2[38;5;241m.[39mCOLOR_BGR2RGB)

[1;31merror[0m: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


