Traceback (most recent call last):
  File "c:\python39\lib\site-packages\myst_nb\core\execute\inline.py", line 127, in code_cell_outputs
    self._client.execute_cell(
  File "C:\Users\matth\AppData\Roaming\Python\Python39\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "c:\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\python39\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Load image
img = cv2.imread('data/smiling_person.jpg')

# Reshape image
gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

# Score the frame
results = score_frame(gray, model) 

# Plot the boxes
image = plot_boxes(results, img, model) 

# Show result
plt.imshow(img)
plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[4], line 2[0m
[0;32m      1[0m [38;5;66;03m# Load image[39;00m
[1;32m----> 2[0m img [38;5;241m=[39m [43mcv2[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mdata/smiling_person.jpg[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      4[0m [38;5;66;03m# Reshape image[39;00m
[0;32m      5[0m gray [38;5;241m=[39m cv2[38;5;241m.[39mcvtColor(img, cv2[38;5;241m.[39mCOLOR_RGB2GRAY)

File [1;32mc:\python39\lib\site-packages\ultralytics\utils\patches.py:26[0m, in [0;36mimread[1;34m(filename, flags)[0m
[0;32m     16[0m [38;5;28;01mdef[39;00m [38;5;21mimread[39m(filename: [38;5;28mstr[39m, flags: [38;5;28mint[39m [38;5;241m=[39m cv2[38;5;241m.[39mIMREAD_COLOR):
[0;32m     17[0m [38;5;250m    [39m[38;5;124;03m"""Read an image from a file.[39;00m
[0;32m     18[0m 
[0;32m     19[0m [38;5;124;03m    Args:[39;00m
[1;32m   (...)[0m
[0;32m     24[0m [38;5;124;03m        (np.ndarray): The read image.[39;00m
[0;32m     25[0m [38;5;124;03m    """[39;00m
[1;32m---> 26[0m     [38;5;28;01mreturn[39;00m cv2[38;5;241m.[39mimdecode([43mnp[49m[38;5;241;43m.[39;49m[43mfromfile[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mnp[49m[38;5;241;43m.[39;49m[43muint8[49m[43m)[49m, flags)

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data/smiling_person.jpg'

